[package]
name = "plowman"
version = "0.0.1-bat-source"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }
serde = "*"
