[package]
name = "plowman"
version = "0.0.1-centered"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }
amethyst_config = "*"
serde = "*"
